version: '3'

services:
  app:
    image: 'flyrest:latest'
    build:
      context: .
    container_name: fly-app
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/kotlin_crud_db
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=123456
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    ports:
      - 8080:8080
  db:
    image: 'mysql:latest'
    container_name: test-mysql
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_DATABASE=kotlin_crud_db
    ports:
      - 3306:3306